- platform: berlin_transport
  departures:
    - name: 'U Bayerischer Platz (Berlin)' # free-form name, only for display purposes
      stop_id: 900055102 # actual Stop ID for the API
      direction: 900017101 # Optional stop_id to limit departures for a specific direction (same URL as to find the stop_id)
      walking_time: 5 # Optional parameter with value in minutes that hides transport closer than N minutes
    # show_official_line_colors: true # Optionally enable official VBB line colors. By default predefined colors will be used.
    - name: 'U Schwartzkopffstr. (Berlin)' # currently you have to add more than one stop to track
      stop_id: 900100501
      # direction: 900000100002 # Optional stop_id to limit departures for a specific direction (same URL as to find the stop_id)
      # walking_time: 5 # Optional parameter with value in minutes that hide transport closer than N minutes
      # show_official_line_colors: true # Optionally enable official VBB line colors. By default predefined colors will be used.
    - name: 'U Mehringdamm (Berlin)' # currently you have to add more than one stop to track
      stop_id: 900017101
      # direction: 900000100002 # Optional stop_id to limit departures for a specific direction (same URL as to find the stop_id)
      walking_time: 5 # Optional parameter with value in minutes that hide transport closer than N minutes
      # show_official_line_colors: true # Optionally enable official VBB line colors. By default predefined colors will be used.
