###############################################################################
#   @author         :   Matthias Bonn
#   @date           :   15/06/2023
#   @package        :   Sysmon
#   @description    :   A collection of Home Assistant and Pi Sensors
###############################################################################
#- platform: systemmonitor
#  resources:
#    - type: last_boot
#    - type: disk_use_percent
#      arg: /
#    - type: memory_free
#      arg: /
#    - type: disk_free
#      arg: /
#    - type: load_1m
#    - type: load_5m
#    - type: load_15m
#    - type: network_in
#      arg: eth0
#    - type: network_out
#      arg: eth0
#    - type: throughput_network_in
#      arg: eth0
#    - type: throughput_network_out
#      arg: eth0
#    - type: ipv4_address
#      arg: eth0
#    - type: processor_use
#    - type: processor_temperature

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'

#  Anzahl der Domain objekte
- platform: template
  sensors:
    #----- Count All Domains
    domains_in_use:
      friendly_name: Domains in use
      value_template: >
        {%- for d in states | groupby('domain') %}
        {% if loop.first %}{{loop.length}} 
        {% endif %}
        {%- endfor %}

    #----- Count All Entities
    total_entities:
      friendly_name: 'Entities'
      icon_template: mdi:code-tags
      value_template: '{{ states | count }}'

    #----- Count Automations
    total_automations:
      friendly_name: 'Automations'
      icon_template: mdi:robot
      value_template: '{{ states.automation | list | length }}'

    #----- Count Binary Sensors
    total_binary_sensors:
      friendly_name: 'Binary Sensors'
      icon_template: mdi:checkbox-multiple-marked-circle
      value_template: '{{ states.binary_sensor | list | length }}'

    #----- Count Cameras
    total_cameras:
      friendly_name: 'Cameras'
      icon_template: mdi:cctv
      value_template: '{{ states.camera | list | length }}'

    #----- Count Counters (haha)
    total_counters:
      friendly_name: 'Counters'
      icon_template: mdi:counter
      value_template: '{{ states.counter | list | length }}'

    #----- Count Device Trackers
    total_devicetrackers:
      friendly_name: 'Devices'
      icon_template: mdi:cellphone-link
      value_template: '{{ states.device_tracker | list | length }}'

    #----- Count Groups
    total_groups:
      friendly_name: 'Groups'
      icon_template: mdi:group
      value_template: '{{ states.group | list | length }}'

    #----- Count Input Booleans
    total_input_booleans:
      friendly_name: 'Input Booleans'
      icon_template: mdi:toggle-switch
      value_template: '{{ states.input_boolean | list | length }}'

    #----- Count Input Datetimes
    total_input_datetimes:
      friendly_name: 'Input Datetimes'
      icon_template: mdi:calendar-clock
      value_template: '{{ states.input_datetime | list | length }}'

    #----- Count Input Numbers
    total_input_numbers:
      friendly_name: 'Input Numbers'
      icon_template: mdi:numeric
      value_template: '{{ states.input_number | list | length }}'

    #----- Count Input Selects
    total_input_selects:
      friendly_name: 'Input Selects'
      icon_template: mdi:format-align-justify
      value_template: '{{ states.input_select | list | length }}'

    #----- Count Input Texts
    total_input_texts:
      friendly_name: 'Input Texts'
      icon_template: mdi:alphabetical
      value_template: '{{ states.input_text | list | length }}'

    #----- Count Lights
    total_lights:
      friendly_name: 'Lights'
      icon_template: mdi:lightbulb-on
      value_template: '{{ states.light | list | length }}'

    #----- Count Media Players
    total_media_players:
      friendly_name: 'Media Players'
      icon_template: mdi:cast-connected
      value_template: '{{ states.media_player | list | length }}'

    #----- Count Persons
    total_persons:
      friendly_name: 'Persons'
      icon_template: mdi:account-multiple
      value_template: '{{ states.person | list | length }}'

    #----- Count Remotes
    total_remotes:
      friendly_name: 'Remotes'
      icon_template: mdi:remote
      value_template: '{{ states.remote | list | length }}'

    #----- Count Scenes
    total_scenes:
      friendly_name: 'Scenes'
      icon_template: mdi:palette
      value_template: '{{ states.scene | list | length }}'

    #----- Count Scripts
    total_scripts:
      friendly_name: 'Scripts'
      icon_template: mdi:script-text-outline
      value_template: '{{ states.script | list | length }}'

    #----- Count Sensors
    total_sensors:
      friendly_name: 'Sensors'
      icon_template: mdi:pulse
      value_template: '{{ states.sensor | list | length }}'

    #----- Count Switches
    total_switches:
      friendly_name: 'Switches'
      icon_template: mdi:power-socket-us
      value_template: '{{ states.switch | list | length }}'

    #----- Count Timers
    total_timers:
      friendly_name: 'Timers'
      icon_template: mdi:timer
      value_template: '{{ states.timer | list | length }}'

    #----- Count Zones
    total_zones:
      friendly_name: 'Zones'
      icon_template: mdi:map-marker-radius
      value_template: '{{ states.zone | list | length }}'
