name: Home Assistant Config Check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  check-config:
    name: Check Home Assistant Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Home Assistant Core
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant

      - name: Validate Home Assistant configuration
        run: |
          hass --script check_config --config .
